version: '3.8'

services:
  entersys-admin:
    build: .
    image: entersys-admin:latest
    container_name: entersys-admin
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # HTTPS Router
      - "traefik.http.routers.entersys-admin.rule=Host(`admin.entersys.mx`)"
      - "traefik.http.routers.entersys-admin.entrypoints=websecure"
      - "traefik.http.routers.entersys-admin.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.entersys-admin.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
